import { AgentRole, PresetScenario } from './types';

export const AGENT_COLORS: Record<AgentRole, string> = {
  ceo: '#f59e0b',
  pm: '#06b6d4',
  engineering: '#8b5cf6',
  marketing: '#ec4899',
  finance: '#22c55e',
  legal: '#3b82f6',
  hr: '#f97316',
  ai_safety: '#ef4444',
  intern: '#84cc16',
};

export const AGENT_LABELS: Record<AgentRole, string> = {
  ceo: 'CEO',
  pm: 'Product Manager',
  engineering: 'Engineering Lead',
  marketing: 'Marketing Lead',
  finance: 'Finance',
  legal: 'Legal',
  hr: 'HR',
  ai_safety: 'AI Safety Officer',
  intern: 'Intern',
};

export const BUZZWORDS = [
  'synergy', 'disruptive', 'AI-native', 'hyper-scale', 'ecosystem',
  'decentralized', 'growth loop', 'autonomous', 'scalable', 'leverage',
  'paradigm shift', 'user journey', 'pain points', 'touchpoints', 'delight',
  'game-changer', 'unicorn', 'runway', 'burn rate', 'MVP', 'PMF',
  'North Star', 'OKR', 'KPI', 'impact', 'actionable', 'drill down',
  'circle back', 'low-hanging fruit', 'deep dive', 'move fast', 'break things',
  'innovate', 'agile', 'sprint', 'standup', 'iteration', 'pivot',
  'first-principles', 'think big', 'moonshot', 'bet', 'vertical',
];

export const EVENT_TYPES = [
  'investor_call',
  'competitor_launch',
  'runway_update',
  'viral_tweet',
  'board_meeting',
  'layoffs',
  'pivot',
  'breakthrough',
] as const;

export const PRESETS: PresetScenario[] = [
  {
    id: 'silicon-valley',
    name: 'Silicon Valley Startup',
    description: 'Classic startup chaos',
    topic: 'Should we add dark mode?',
    companyType: 'Silicon Valley Startup',
    chaosLevel: 70,
    budgetPressure: 60,
    vcPressure: 80,
    aiHype: 90,
    layoffsMode: false,
    blockchainMode: false,
    aiFirstMode: true,
  },
  {
    id: 'faang',
    name: 'FAANG Product Review',
    description: 'Corporate rigor meets AI hype',
    topic: 'Should we integrate AI summarization?',
    companyType: 'FAANG',
    chaosLevel: 30,
    budgetPressure: 20,
    vcPressure: 10,
    aiHype: 85,
    layoffsMode: false,
    blockchainMode: false,
    aiFirstMode: true,
  },
  {
    id: 'web3',
    name: 'Web3 Startup in Panic',
    description: 'Desperate times',
    topic: 'Should we pivot to AI?',
    companyType: 'Web3 Startup',
    chaosLevel: 90,
    budgetPressure: 95,
    vcPressure: 90,
    aiHype: 100,
    layoffsMode: true,
    blockchainMode: true,
    aiFirstMode: true,
  },
  {
    id: 'ai-safety',
    name: 'AI Safety Company',
    description: 'Existential concerns only',
    topic: 'Should we add a feature?',
    companyType: 'AI Safety Company',
    chaosLevel: 50,
    budgetPressure: 30,
    vcPressure: 40,
    aiHype: 70,
    layoffsMode: false,
    blockchainMode: false,
    aiFirstMode: false,
  },
  {
    id: 'government',
    name: 'Government Procurement',
    description: 'Years of approvals',
    topic: 'Should we upgrade the dashboard?',
    companyType: 'Government',
    chaosLevel: 20,
    budgetPressure: 10,
    vcPressure: 5,
    aiHype: 30,
    layoffsMode: false,
    blockchainMode: false,
    aiFirstMode: false,
  },
  {
    id: 'yc-startup',
    name: 'YC Startup Before Demo Day',
    description: 'Everything is on fire',
    topic: 'Should we ship anything?',
    companyType: 'YC Startup',
    chaosLevel: 95,
    budgetPressure: 90,
    vcPressure: 100,
    aiHype: 80,
    layoffsMode: true,
    blockchainMode: false,
    aiFirstMode: true,
  },
  {
    id: 'enterprise',
    name: 'Enterprise SaaS',
    description: 'Bureaucratic excellence',
    topic: 'Should we add SSO?',
    companyType: 'Enterprise SaaS',
    chaosLevel: 40,
    budgetPressure: 20,
    vcPressure: 15,
    aiHype: 60,
    layoffsMode: false,
    blockchainMode: false,
    aiFirstMode: true,
  },
  {
    id: 'open-source',
    name: 'Open Source Maintainers',
    description: 'Passionate chaos',
    topic: 'Should we accept this PR?',
    companyType: 'Open Source',
    chaosLevel: 60,
    budgetPressure: 80,
    vcPressure: 20,
    aiHype: 50,
    layoffsMode: false,
    blockchainMode: false,
    aiFirstMode: false,
  },
];

export const DEFAULT_METRICS = {
  productivity: 100,
  burnRate: 0,
  morale: 100,
  technicalDebt: 0,
  buzzwordDensity: 0,
  shippingProbability: 80,
  pivotLikelihood: 10,
  reorgRisk: 5,
  investorSatisfaction: 80,
};